//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jsaosorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseHistorical
    {
        public string Id { get; set; }
        public string Domain { get; set; }
        public string old { get; set; }
        public string new_data { get; set; }
        public string Current_Status { get; set; }
        public string type { get; set; }
        public string Super_Agency { get; set; }
        public string datechange { get; set; }
    }
}
