//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualOffDay
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> OffDay { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserLeavePolicyId { get; set; }
    }
}
