//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLog
    {
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string AspNetUserId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Item Item { get; set; }
    }
}
