//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> PassengerId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public bool IsBlackListed { get; set; }
        public Nullable<System.DateTime> DateBlackList { get; set; }
        public string Floor { get; set; }
        public string Bell { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Place Place { get; set; }
    }
}
